### ISSUE TITLE
[1.17] The map has missing blocks

### ISSUE THREAD

**Issue by Hugman76** [NucleoidMC/Siege#23]
`minecraft:grass_path` has been renamed `minecraft:dirt_path` in 1.17 and that leaves holes in the map.

**Comment by Restioson** [comment]
Hmm... I wonder what the best way is to fix this? Is it intact on the build server? In that case, a re-export should be enough I think.

**Comment by Hugman76** [comment]
![2021-08-13_13 05 44](https://user-images.githubusercontent.com/36963654/129348160-08c500e9-609d-4f94-a61e-f6c0898981c0.png)
Yup! `/map join siege:villagers_vs_pillagers`

**Comment by Restioson** [comment]
Alright, awesome. I'll try get to it soon but if anyone else submits a PR before I will merge it

**Comment by Hugman76** [comment]
I think this was fixed?

**Comment by Patbox** [comment]
Yep, dfu is now applied to blocks
