### ISSUE TITLE
Planks that replace plants cannot be broken

### ISSUE THREAD

**Issue by haykam821** [NucleoidMC/Siege#27]
When using the constructor kit, planks can be placed in a way that they replace grass, tall grass, and ferns. However, because the map's initial blocks cannot be broken, the planks replacing plants cannot be broken either.

**Comment by Restioson** [comment]
I was thinking of removing the protection on these kind of foliage blocks to allow for a bit more dynamism too - the feeling of looting and burning as an attacker... But worthwhile to keep in mind for other cases too
