### ISSUE TITLE
Siege: the Profile Inventory wouldn't reset sometimes If a player visited and left that minigame in sometime

### ISSUE THREAD

**Issue by marpl3x** [NucleoidMC/Siege#53]
### Steps to reproduce:
1. Use an item called "Navigator".
2. Join any part games of Siege.
3. In sometime, leave the game using a command /hub.

### Observed Results
The profile inventory wouldn't reset sometimes because that "Kit Select" item stays and counts an accidental number in the Profile Inventory.

### Expected Results
Profile Inventory should reset normally after visiting or even leaving that minigame, but should not get a count of that item.

![2024-06-22_14 41 01](https://github.com/NucleoidMC/Siege/assets/117781728/8727b570-4010-4633-90a3-a28f1891fe7e)
![2024-06-22_15 01 09](https://github.com/NucleoidMC/Siege/assets/117781728/10b071eb-095c-415d-9ed1-9c2ba19bb158)

**Comment by Restioson** [comment]
Limited time exclusive collectors item 😉

I'll fix this when I get home from holiday, unless anyone else wants to take it up meanwhile

**Comment by haykam821** [comment]
The boss bar also seems to be kept when leaving the game.
